# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceeed73a98cc2f9ef247e2c2a0a2088a47e994dff1a67d6bdfcf8e36e8187c6f28aa4a5c702aa01919550a86e0231e6975580e82810d3d8caa53fe36c54983a6

test:
  secret_key_base: 9477ba8580d55c0b9b25cb848964706d4a53c005ed76e8224e33679c7031e14eb027a33c4ffef382d7c18785b053a116ff279bd234577e6322de8785deb1cb9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
